services:
  mongo:
    image: mongo:7
    container_name: gestion-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./gestion-academique-backend
    image: hedy123fth/gestion-backend:latest
    container_name: gestion-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/gestion_academique
      - JWT_SECRET=change_me
      - JWT_EXPIRES_IN=7d
      - NODE_ENV=production
      
    depends_on:
      - mongo

  frontend:
    build: ./gestion-academique-frontend
    image: hedy123fth/gestion-frontend:latest
    container_name: gestion-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo_data:
